org: ryanktt
app: questionnaire-app
service: questionnaire-app

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, "local"}
  region: ${opt:region, "us-east-1"}
  environment: ${file(./serverless-env.js):${self:provider.stage}}

functions:
  upsert-questionnaire-response-consumer:
    handler: src/bootstrap/consumers/upsert-questionnaire-response/lambda.handler
    events:
      - stream:
          arn: arn:aws:kinesis:us-east-1:874738831934:stream/questionnaire-upsert-response-stream
