org: ryanktt
app: questionnaire-app
service: questionnaire-app

plugins:
  - serverless-webpack
  - serverless-plugin-optimize
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, "local"}
  region: ${opt:region, "us-east-1"}
  environment: ${file(./serverless-env.js):${self:provider.stage}}

custom:
  webpack:
    webpackConfig: './webpack.config.js'
  serverless-offline:
    httpPort: 4000
    noPrependStageInUrl: true

functions:
  main:
    handler: src/bootstrap/lambda.handler
    events:
      - http:
          path: 'graphql'
          method: any
  upsert-questionnaire-response-consumer:
    handler: src/bootstrap/consumers/upsert-questionnaire-response/lambda.handler
    events:
      - stream:
          arn: arn:aws:kinesis:us-east-1:874738831934:stream/questionnaire-upsert-response-stream
