org: ryanktt
app: questionnaire-app
service: questionnaire-app

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - kinesis:GetRecords
            - kinesis:GetShardIterator
            - kinesis:DescribeStream
            - kinesis:ListStreams
            - kinesis:PutRecord
            - kinesis:PutRecords
          Resource: arn:aws:kinesis:us-east-1:874738831934:stream/questionnaire-upsert-response-stream

functions:
  questionnaire-response-upsertion-consumer:
    handler: src/bootstrap/response-upsertion-consumer/lambda.handler
    events:
      - stream:
          arn: arn:aws:kinesis:us-east-1:874738831934:stream/questionnaire-upsert-response-stream
