org: ryanktt
app: questionnaire-app
service: questionnaire-app

plugins:
  - serverless-webpack
  - serverless-offline

build:
  esbuild: false

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, "local"}
  region: ${opt:region, "us-east-1"}
  environment: ${file(./serverless-env.js):${self:provider.stage}}
  iam:
    role:
      - arn:aws:iam::874738831934:role/questionnaire-main-lambda-${self:provider.stage}-role

package:
  individually: true

custom:
  webpack:
    webpackConfig: './webpack.config.js'
    includeModules: true
    packager: yarn
  serverless-offline:
    httpPort: 5000
    noPrependStageInUrl: true

functions:
  main:
    handler: src/bootstrap/lambda.handler
    timeout: 30
    events:
      - http:
          path: 'graphql'
          method: any

  upsert-questionnaire-response-consumer:
    handler: src/bootstrap/consumers/upsert-questionnaire-response/lambda.handler
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:874738831934:${self:provider.stage}-questionnaire-app-upsert-questionnaire-response-queue
